# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:

  - name: intialize
    init: |
      echo 'init script' # runs during prebuild
      export PIP_USER=false
      pip3 install -r requirements.txt
      DEBUG=True FLASK_APP=app.py flask db init
      DEBUG=True FLASK_APP=app.py flask db migrate
      DEBUG=True FLASK_APP=app.py flask db upgrade
      
    command: FLASK_APP=app.py FLASK_ENV=development flask run

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
