"""empty message

Revision ID: 6519a07baf2a
Revises: 90c37344098b
Create Date: 2021-08-11 18:19:15.244228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6519a07baf2a'
down_revision = '90c37344098b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_offices',
    sa.Column('agency_office_code', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('usa_state', sa.String(length=20), nullable=True),
    sa.Column('agency_office_name', sa.String(length=255), nullable=True),
    sa.Column('can_set_status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('agency_office_code')
    )
    op.create_index(op.f('ix_agency_offices_uuid'), 'agency_offices', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agency_offices_uuid'), table_name='agency_offices')
    op.drop_table('agency_offices')
    # ### end Alembic commands ###
