"""empty message

Revision ID: 6d3aa30c778b
Revises: 36de9178dac6
Create Date: 2021-11-23 15:53:41.256188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3aa30c778b'
down_revision = '36de9178dac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('active_status', sa.String(length=255), nullable=True))
    op.add_column('status', sa.Column('status_code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'status_code')
    op.drop_column('status', 'active_status')
    # ### end Alembic commands ###
