"""empty message

Revision ID: bf10f636daf6
Revises: a18577ac4f2a
Create Date: 2022-03-21 12:46:06.640743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf10f636daf6'
down_revision = 'a18577ac4f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('manage_all_orders', sa.String(length=1), nullable=True))
    op.add_column('users', sa.Column('update_all_statuses', sa.String(length=1), nullable=True))
    op.add_column('users', sa.Column('view_all_orders', sa.String(length=1), nullable=True))
    op.add_column('users', sa.Column('manage_all_users', sa.String(length=1), nullable=True))
    op.add_column('users', sa.Column('manage_office_users', sa.String(length=1), nullable=True))
    op.add_column('users', sa.Column('update_own_password', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'update_own_password')
    op.drop_column('users', 'manage_office_users')
    op.drop_column('users', 'manage_all_users')
    op.drop_column('users', 'view_all_orders')
    op.drop_column('users', 'update_all_statuses')
    op.drop_column('users', 'manage_all_orders')
    # ### end Alembic commands ###
